Testing Workflow

diff --git a/.github/workflows/packer-merge.yml b/.github/workflows/packer-merge.yml
--- a/.github/workflows/packer-merge.yml
+++ b/.github/workflows/packer-merge.yml
@@ -39,7 +39,7 @@ jobs:
             cp cloud/*.jar packer
             cd packer && ls -al
           env:
-            MYSQL_DB_USERNAME: ${{ secrets.MYSQL_DB_USERNAME }}
+            MYSQL_DB_USERNAME: ${{ secrets.MYSQL_DB_USERNAM }}
             MYSQL_DB_PASSWORD: ${{ secrets.MYSQL_DB_PASSWORD }}
             MYSQL_DB_DATABASE: ${{ secrets.MYSQL_DB_DATABASE }}
             MYSQL_DB_HOST: ${{ secrets.MYSQL_DB_HOST }}
@@ -80,12 +80,20 @@ jobs:
         - name: Format check Packer
           run: |
             cd packer
+            CHANGES=$(git diff --name-only)
             packer fmt -check .
+            if [ $? -ne 0 ]; then
+              echo "Packer template was modified by 'packer fmt' command."
+              echo "$CHANGES"
+            fi
 
         - name: Validate Packer
           run: |
             cd packer
             packer validate .
+            if [ $? -ne 0 ]; then
+              echo "Packer template validation failed."
+            fi
 
         - name: Check if any job failed
           if: ${{ failure() }}
diff --git a/.github/workflows/packer.yml b/.github/workflows/packer.yml
--- a/.github/workflows/packer.yml
+++ b/.github/workflows/packer.yml
@@ -92,3 +92,7 @@ jobs:
         run: |
           cd packer
           packer validate .
+          if [ $? -ne 0 ]; then
+            echo "Packer template validation failed."
+            exit 1
+          fi
